### PR TITLE
Fix unhandled errors causing ida to crash

### PR DESCRIPTION
**Pull request by a1gx**

### CODE REVIEW

**Comment by illera88** [comment]
Hi,

I don't believe that the `processing` method could raise an error. There is already an error type which should handled non supported instructions:

```
FAULT_UD,         /*!< Fault raised: Instruction not supported. */
```

I'm opening an issue in the Triton project to ask about it.

What instructions are not supported for you?

**Comment by illera88** [comment]
for reference: https://github.com/JonathanSalwan/Triton/issues/1252

**Comment by 0ca** [comment]
I think @a1gx was getting the same errors as https://github.com/illera88/Ponce/issues/137, and he was trying to fix it.

Use the latest release, 0.3.7. It should work.

**Comment by illera88** [comment]
Closing for now. Let us know if it doesn't fix the problems so we will reopen. 

Cheers

**Pull request closed without merging**
